During exception return exceptions can occur, for example asynchronous exceptions, or the exception return might itself cause an exception.<BR>Any exception that occurs during exception return is a <SPAN class=cloze>[...]</SPAN>.<BR>When the exception return sequence itself causes an exception, the latter exception is a derived exception.